name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_shravaninakade }}
        password: ${{ secrets.DOCKER_Shravani@10 }}

    - name: Build Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_shravaninakade }}/mean-backend:latest ./backend

    - name: Push Backend Image
      run: |
        docker push ${{ secrets.DOCKER_shravaninakade }}/mean-backend:latest

    - name: Build Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_shravaninakade }}/mean-frontend:latest ./frontend

    - name: Push Frontend Image
      run: |
        docker push ${{ secrets.DOCKER_shravaninakade }}/mean-frontend:latest